y = m * x + b

m =

In [2]:
import numpy as np
import pandas as pd

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [32]:
class simple_linear_regression:

    def __init__(self):
        self.m = None
        self.b = None

    def fit(self, X_train, y_train):
        # Convert Pandas DataFrames/Series to 1D NumPy arrays
        X_train = np.array(X_train).ravel()
        y_train = np.array(y_train).ravel()
        
        num = 0
        den = 0
        
        x_mean = X_train.mean()
        y_mean = y_train.mean()
        
        for i in range(X_train.shape[0]):
            num += (X_train[i] - x_mean) * (y_train[i] - y_mean)
            den += (X_train[i] - x_mean) ** 2
            
        self.m = num / den
        self.b = y_mean - (self.m * x_mean)

    def predict(self,X_test):

        return (self.m * X_test) + self.b

In [11]:
# storing data
df = pd.read_csv('data\simpleLinearRegression.csv')

X = df.iloc[:,[0]]
y = df.iloc[:,[1]]

#Splitting data
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

X_test

    YearsExperience
12              6.8
4               2.9
18              9.5
0               1.1

In [13]:
#FROM sk learn library

model = LinearRegression()

model.fit(X_train,y_train)

model.predict(X_test[0:1])

array([[86.30316368]])

In [33]:
# FROM hard coded

mymodel = simple_linear_regression()

In [34]:
mymodel.fit(X_train,y_train)

mymodel.predict(X_test[0:1])

    YearsExperience
12        86.303164